import {
  fetchAllData,
  getTodayStats,
  getWeekStats,
  getMonthStats,
  getYearStats,
  getComparisons,
  waitForAdminAccess,
  guardAdmin
} from './stats.js';

import jsPDF from "https://cdn.jsdelivr.net/npm/jspdf@2.5.1/+esm";

/* ================================
   🧠 CONFIG
================================ */
const logoUrl = "https://dummyimage.com/100x40/0B3D2E/ffffff&text=ES+SHOP";

/* ================================
   🧾 FORMATTERS
================================ */
const money = v => (v || 0).toFixed(2);
const dateNow = () => new Date().toLocaleString();

/* ================================
   🧱 PDF BUILDER CORE
================================ */
function createDoc() {
  return new jsPDF();
}

/* ================================
   🟩 HEADER
================================ */
function generateHeader(doc, title) {
  doc.setFontSize(16);
  doc.text("ES SHOP REPORT", 14, 15);

  doc.setFontSize(10);
  doc.text(`Type: ${title}`, 14, 22);
  doc.text(`Généré le: ${dateNow()}`, 14, 27);

  doc.line(14, 30, 196, 30);
}

/* ================================
   🟦 KPI
================================ */
function generateKPIs(doc, stats, startY) {
  const kpis = [
    ["Ventes", money(stats.total_sales)],
    ["Profit", money(stats.total_profit)],
    ["Dépenses", money(stats.total_expenses)],
    ["Net", money(stats.net)],
    ["Cash réel", money(stats.real_cash)],
    ["Dettes", money(stats.debts_remaining)],
    ["Produits", stats.products_sold],
    ["Ventes (nb)", stats.nb_sales]
  ];

  let y = startY;

  kpis.forEach((k, i) => {
    doc.text(`${k[0]}: ${k[1]}`, 14 + (i % 2) * 90, y);
    if (i % 2 !== 0) y += 6;
  });

  return y + 4;
}

/* ================================
   🟥 REAL VS IDEAL
================================ */
function generateReality(doc, stats, y) {
  doc.text("Réalité vs Projection", 14, y);
  y += 6;

  doc.text(`Net réel: ${money(stats.net)}`, 14, y);
  doc.text(`Profit idéal: ${money(stats.ideal_profit)}`, 100, y);

  return y + 8;
}

/* ================================
   🟨 TABLE SIMPLE
================================ */
function drawTable(doc, headers, rows, startY) {
  let y = startY;

  doc.setFontSize(10);
  doc.text(headers.join(" | "), 14, y);
  y += 5;

  rows.forEach(r => {
    doc.text(r.join(" | "), 14, y);
    y += 5;

    if (y > 280) {
      doc.addPage();
      y = 20;
    }
  });

  return y;
}

/* ================================
   🟫 DETTES
================================ */
function generateDebts(doc, stats, y) {
  doc.text("Dettes", 14, y);
  y += 6;

  doc.text(`Total restant: ${money(stats.debts_remaining)}`, 14, y);
  doc.text(`Impact cash: ${money(stats.total_sales - stats.real_cash)}`, 100, y);

  return y + 8;
}

/* ================================
   🟧 FOOTER
================================ */
function generateFooter(doc) {
  doc.setFontSize(8);
  doc.text("Generated by ES Shop SaaS", 14, 290);
}

/* ================================
   📊 TABLE JOUR / SEMAINE / MOIS
================================ */
function buildFlatTable(data) {
  return data.sales.map(s => [
    new Date(s.createdAt?.seconds * 1000).toLocaleDateString(),
    money(s.total_amount),
    money(s.total_profit),
    "-",
    money(s.total_profit)
  ]);
}

/* ================================
   📆 TABLE ANNUELLE AVANCÉE
================================ */
function buildYearTable(yearData) {
  const rows = [];

  yearData.monthly.forEach((m, i) => {
    const weeks = 4;
    const weekly = m.net / weeks;

    rows.push([
      `M${i + 1}`,
      money(m.sales),
      money(m.profit),
      money(m.expenses),
      money(m.net),
      money(weekly),
      "—"
    ]);
  });

  return rows;
}

/* ================================
   🚀 GENERATE PDF
================================ */
async function buildPDF(type) {
  await waitForAdminAccess();
  guardAdmin();

  const data = await fetchAllData();
  const doc = createDoc();

  let stats;
  let rows = [];
  let headers = ["Date", "Ventes", "Profit", "Dépenses", "Net"];

  /* ================================
     🔀 SWITCH TYPE
  ================================= */
  if (type === "today") {
    stats = getTodayStats(data);
    rows = buildFlatTable(data);

  } else if (type === "week") {
    stats = getWeekStats(data);
    rows = buildFlatTable(data);

  } else if (type === "month") {
    stats = getMonthStats(data);
    rows = buildFlatTable(data);

  } else if (type === "year") {
    const year = new Date().getFullYear();
    const yearData = getYearStats(data, year);

    stats = yearData.totals;

    headers = ["Mois", "Ventes", "Profit", "Dépenses", "Net", "Hebdo", "Trend"];
    rows = buildYearTable(yearData);
  }

  /* ================================
     🧾 BUILD DOC
  ================================= */
  generateHeader(doc, type.toUpperCase());

  let y = 35;
  y = generateKPIs(doc, stats, y);
  y = generateReality(doc, stats, y);
  y = drawTable(doc, headers, rows, y);
  y = generateDebts(doc, stats, y);

  generateFooter(doc);

  doc.save(`report-${type}.pdf`);
}

/* ================================
   🎯 EVENTS
================================ */
document.getElementById("export-today").onclick = () => buildPDF("today");
document.getElementById("export-week").onclick = () => buildPDF("week");
document.getElementById("export-month").onclick = () => buildPDF("month");
document.getElementById("export-year").onclick = () => buildPDF("year");